//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-0f095f89ae15be883"
mykey = "" # your key is written here !!
tags = ["postgresql", "nodejs", "react"]
instancetype = "t2.micro"
controlinstancetype = "t3a.medium"
num = 3
region = "" # your region is written here !!
mysecgr = "ansible-project-sec-gr"
user = "ansible"