- name: configure postgresql
  hosts: _ansible_postgresql
  become: true
  vars_files:
    - secret.yaml
  tasks:
    - name: update packages
      yum:
        name: "*"
        state: latest

    - name: uninstall old version
      yum:
        name: "{{ item }}"
        state: removed
      loop:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

    - name: install yum-utils
      yum: 
        name: yum-utils
        state: latest

    - name: add docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: install docker
      package:
        name: docker-ce
        state: latest
    
    - name: install pip
      package:
        name: python3-pip
        state: present
     
    - name: Install docker sdk
      pip:
        name: docker
    
    - name: add ec2-user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes

    - name: start docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: create build directory
      file:
        path: /home/ec2-user/postgresql
        state: directory
        owner: root
        group: root
        mode: "0755"  
    
    - name: copy docker file
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/postgres/init.sql
        dest: /home/ec2-user/postgresql

    - name: copy docker file
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/postgres/Dockerfile
        dest: /home/ec2-user/postgresql

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=nihat_postgre' && docker stop nihat_postgre && docker rm -fv nihat_postgre && docker image rm -f nihatcw/postgre || echo 'Not Found'"    

    - name: docker build
      community.docker.docker_image:
        name: postgre:1.0
        build:
          path: /home/ec2-user/postgresql
        tag: database
        source: build
        state: present
        
    - name: create postgresql docker container
      docker_container:
        name: nihat_postgre
        image: postgre:1.0
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "{{ password }}"
        volumes:
          - /db-data:/var/lib/postgresql/data
      register: container_info

    - name: print the container info
      debug:
        var: container_info